version: '3.4'

services:
  redis:
    image: redis:latest
    ports:
      - "5379:6379"
  conch.shop:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  conch.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  conch.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  conch.goods:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  conch.stock:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  dapr-placement:
    command: [ "./placement", "-port", "50000", "-log-level", "debug" ]
    ports:
      - "50000:50000"
