version: '3.4'

services:
  conch.shop:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  conch.order:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  conch.account:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  conch.goods:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  conch.stock:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

