apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: conch.shop
spec:
  type: state.redis
  version: v1
  metadata:
    - name: redisHost
      value: localhost:6379
    - name: redisPassword
      value: ""
    - name: actorStateStore
      value: "true"
scopes:
  - conch.order
  - conch.stock
  - ordering-api