// <auto-generated />
using System;
using Conch.Stock;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Conch.Stock.Migrations
{
    [DbContext(typeof(StockDBContext))]
    [Migration("20211206080727_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Conch.Stock.StockGoods", b =>
                {
                    b.Property<Guid>("StockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoodsId")
                        .HasColumnType("uuid");

                    b.Property<string>("GoodsName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Num")
                        .HasColumnType("integer");

                    b.HasKey("StockId", "GoodsId");

                    b.ToTable("StockGoods");
                });

            modelBuilder.Entity("Conch.Stock.StockMaster", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Name")
                        .HasMaxLength(64)
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("StockMaster");
                });
#pragma warning restore 612, 618
        }
    }
}
